// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlCCgr9C6r09mIN3Qhu3lA2shJ97CHMoM',
    appId: '1:454115433875:web:155d963c0190c448c3dc66',
    messagingSenderId: '454115433875',
    projectId: 'to-do-app-23df2',
    authDomain: 'to-do-app-23df2.firebaseapp.com',
    storageBucket: 'to-do-app-23df2.appspot.com',
    measurementId: 'G-3DZ7HX5TPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzlBwohtQByU83Q8hbZHsC0EkbMlxFes0',
    appId: '1:454115433875:android:f7fdf9c19f549c00c3dc66',
    messagingSenderId: '454115433875',
    projectId: 'to-do-app-23df2',
    storageBucket: 'to-do-app-23df2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK31b5AtIZlmpO9p68HuIS_Xvkm-A6_d0',
    appId: '1:454115433875:ios:87c07f7f257d9063c3dc66',
    messagingSenderId: '454115433875',
    projectId: 'to-do-app-23df2',
    storageBucket: 'to-do-app-23df2.appspot.com',
    iosBundleId: 'com.eraasorf.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK31b5AtIZlmpO9p68HuIS_Xvkm-A6_d0',
    appId: '1:454115433875:ios:87c07f7f257d9063c3dc66',
    messagingSenderId: '454115433875',
    projectId: 'to-do-app-23df2',
    storageBucket: 'to-do-app-23df2.appspot.com',
    iosBundleId: 'com.eraasorf.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlCCgr9C6r09mIN3Qhu3lA2shJ97CHMoM',
    appId: '1:454115433875:web:a2f575d5df01aaddc3dc66',
    messagingSenderId: '454115433875',
    projectId: 'to-do-app-23df2',
    authDomain: 'to-do-app-23df2.firebaseapp.com',
    storageBucket: 'to-do-app-23df2.appspot.com',
    measurementId: 'G-49462K6YN1',
  );
}
